#ESTO ES UN PROTOTIPO DE MAKEFILE.
OBJ=obj
BIN=bin
LIB=lib
SRC=src
INC=include

all: $(BIN)/principal

clean:
		echo "Limpieza de archivos objetos y bibliotecas..."
		rm $(OBJ)/*.o $(LIB)/*a

mrproper: clean
		rm $(BIN)/principal

$(OBJ)/punto.o: $(SRC)/punto.cpp $(INC)/punto.h
		g++ -c -o $(OBJ)/punto.o -I$(INC) $(SRC)/punto.cpp

$(OBJ)/circulo.o: $(SRC)/circulo.cpp $(INC)/circulo.h $(INC)/punto.h
		g++ -c -o $(OBJ)/circulo.o -I$(INC) $(SRC)/circulo.cpp

$(OBJ)/utilidades.o: $(SRC)/utilidades.cpp $(INC)/utilidades.h $(INC)/punto.h $(INC)/circulo.h
		g++ -c -o $(OBJ)/utilidades.o -I$(INC) $(SRC)/utilidades.cpp

$(LIB)/$(LIB)formas.a: $(OBJ)/punto.o $(OBJ)/utilidades.o $(OBJ)/circulo.o
		ar rvs $(LIB)/$(LIB)formas.a  $(OBJ)/punto.o $(OBJ)/utilidades.o $(OBJ)/circulo.o

$(OBJ)/principal.o: $(SRC)/principal.cpp $(INC)/punto.h $(INC)/circulo.h $(INC)/utilidades.h
		g++ -c -o $(OBJ)/principal.o -I$(INC) $(SRC)/principal.cpp

$(BIN)/principal: $(OBJ)/principal.o $(LIB)/$(LIB)formas.a
		g++ -L$(LIB)/ -o $(BIN)/principal $(OBJ)/principal.o -lformas